version: '2'
services:
  web:
    image: php:7.2-cli
    build: .
    ports:
     - "80:80"
    links:
     - mysql
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_PASSWORD="root"
      - MYSQL_DATABASE="webdb"
